#!/usr/bin/env python3

# Author: Connor Bray
# Date: 6/8/2022
# Purpose: Run programs from command line and open in browser

# Imports
import argparse
import webbrowser
import subprocess
import os
from time import sleep

# CONFIG
USER = 'connorbray'
HOSTNAME = 'eerpdev.dev.tylertechnologies.com'

# Pass args: 

'''


r/application/txbldtmt?Arg=hello&Arg=world&Arg=third

is the equivalent to "mrun txbldtmt hello world third"

'''

# Main function
# program : String to represent program name
# build : Boolean to represent if program should be built first
def main(program, build, arg_list):

    # Build first if b flag is given
    if build:
        cwd = os.curdir
        os.chdir('/workspace/src')
        subprocess.run(['bb', program])
        os.chdir(cwd)

    # Format URL
    args = '?'
    for arg in arg_list:
        args += f"Arg={arg}&"

    url = f'https://{USER}.{HOSTNAME}/gas/ua/r/application/{program}{args}'

    print(f"url: {url}")


    # Does GAS need to be restarted every time?


    # Kill any old GAS sessions
    subprocess.run(['pkill', 'fastcgidispatch'])
    sleep(3)

    # Start GAS in background
    subprocess.Popen(['startgas'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

    # Open URL in new tab
    webbrowser.open_new_tab(url)

    return 0


if __name__ == '__main__':

    # Create program arguments
    parser = argparse.ArgumentParser('run')
    parser.add_argument('program', type=str, help='munis program to run in browser', )
    parser.add_argument('-b', action='store_true')
    parser.add_argument('program_args', nargs='*', type=str, help='pass args into program')
    args = parser.parse_args()

    # Pass arguments to main
    main(args.program, args.b, args.program_args)
