#!/usr/bin/env python3

# Author: Connor Bray
# Date: 6/8/2022
# Purpose: Run programs from command line and open in browser

# Imports
import argparse
import webbrowser
import subprocess
import os
# import json

# Pull config from /usr/local/etc
# Ask for firstlast in setup. If they enter work email or AD name, remove the . and the @tylertech.com from the end

# CONFIG
USER = 'connorbray'
HOSTNAME = 'eerpdev.dev.tylertechnologies.com'

# Read from config file
# Set name to env variable? check if it is set. if it is not, read from config file

# Pass args: 

'''


r/application/txbldtmt?Arg=hello&Arg=world&Arg=third

is the equivalent to "mrun txbldtmt hello world third"

'''

# Main function
# program : String to represent program name
# arg_list : 
def main(program, arg_list):
    '''
    Add doc string
    '''


    # Check if GAS is running
    gasOffline = not (subprocess.run(['pgrep', '-lf', 'fastcgidispatch'], capture_output=True, text=True).stdout)

    # Start GAS in the background if it is not running
    if gasOffline:
        subprocess.Popen(['startgas'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

    # Build program
    cwd = os.curdir
    os.chdir('/workspace/src')
    subprocess.run(['bb', program])
    os.chdir(cwd)
        
    # Format URL
    args = '?'
    for arg in arg_list:
        args += f"Arg={arg}&"
    url = f'https://{USER}.{HOSTNAME}/gas/ua/r/application/{program}{args}'

    # Open URL in new tab
    webbrowser.open_new_tab(url)

    return 0


if __name__ == '__main__':

    # Create program arguments
    parser = argparse.ArgumentParser('run')
    parser.add_argument('program', type=str, help='munis program to run in browser', )
    parser.add_argument('program_args', nargs='*', type=str, help='pass args into program')
    args = parser.parse_args()

    # Pass arguments to main
    main(args.program, args.program_args)


def getvar():
    try: 
        user = os.environ['USER']
    except KeyError: # get value from config file and set env variable to match that
        pass
