#!/usr/bin/env python3

# Author: Connor Bray
# Date: 6/8/2022
# Purpose: Run programs from command line and open in browser

# Imports
import argparse
import webbrowser
import subprocess
import os
import json

# CONFIG
HOSTNAME = os.getenv('EERP_DEV_DOMAIN')

# Main function
# program : String to represent program name
# arg_list : Arguments to pass into program
# debug : Boolean if debugging should be enabled
def main(program, arg_list, debug):
    '''
    Doc string
    '''

    # Check if GAS is running
    gasOffline = not (subprocess.run(['pgrep', '-lf', 'fastcgidispatch'], capture_output=True, text=True).stdout).strip()

    # Start GAS in the background if it is not running
    if gasOffline:
        
        # Pipe STDERR to /dev/null
        gas = 'startgas 2> /dev/null'
        
        # Include STDERR if debug is true
        if debug:
            gas = 'startgas'
        
        # Start gas in background tmux window
        subprocess.run(['tmux', 'new', '-d', '-s', 'crun', gas])
    
    # If gas is running in background and debugging is enabled,
    # kill current gas service and start in debug mode
    else:
        if debug:
            
            # kill gas service
            subprocess.run(['pkill', 'fastcgidispatch'])
            
            print('Restarting GAS in debug mode...')

            # wait for tmux session to come offline before restarting
            tmux_exists = not subprocess.run(['tmux', 'has-session', '-t', 'crun']).returncode
            while (tmux_exists):
                tmux_exists = not subprocess.run(['tmux', 'has-session', '-t', 'crun'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).returncode
            
            # Start gas in tmux window
            subprocess.run(['tmux', 'new', '-d', '-s', 'crun', 'startgas'])
            print('Gas started in debug mode. Run \'gaslog\' to view')


    # Build program
    cwd = os.curdir
    os.chdir('/workspace/src')
    subprocess.run(['bb', program])
    os.chdir(cwd)
        
    # Format URL
    args = '?'
    for arg in arg_list:
        args += f"Arg={arg}&"
    url = f'https://{HOSTNAME}/gas/ua/r/application/{program}{args}'

    # Open URL in new tab
    webbrowser.open_new_tab(url)

    return 0

if __name__ == '__main__':

    # Create program arguments
    parser = argparse.ArgumentParser('run')
    parser.add_argument('program', type=str, help='munis program to run in browser', )
    parser.add_argument('program_args', nargs='*', type=str, help='pass args into program (optional)')
    parser.add_argument('-d', action='store_true', help='debug mode - includes STDERR in console output')
    args = parser.parse_args()

    # Pass arguments to main
    main(args.program, args.program_args, args.d)